### PR TITLE
Data architect

### PR DESCRIPTION
**Pull request by abeidahmed**
- Add user, friendship ERD model
- Clean up gemfile

### CODE REVIEW

**Comment by mimipeshy** [comment]
#### STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hey team @abeidahmed 👋🏾 👋🏾 you have tried to implement a good ERD, however, let's make it even better. 

- [x] You have not implemented the `comment` table which allows users to comments on posts
- [x] You have not implemented the `like` table where users can like or dislike comments/posts
- [x] You have not implemented the `post` table where users can post information
- [x] Since `requester_id` and `addresee_id` are both instances of the user model, there should be an inverse relationship between the user and the friendship model. This implies that a user can send many friend requests and can also receive many friend requests, but a friend request, either sent or received, can belong to just only one user. See the diagram below for details:

image


That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes Required**
Hi!!
Good job with your ERD, but there is one change that you have to do before moving to the next milestone: 

- [ ] [REQUIRED] Please separate this to make your ERD easy to understand and to make it to more clearer:


I am sure that it will be super quick to implement!
Kindly fix the pointed out issue before requesting the next code review.
Happy coding
Rindra Josia

**Review by rindrajosia — APPROVED** [review]
**STATUS: APPROVED** :medal_sports: 
**Congratulations**, your project is approved. 
The ERD image has everything required. Milestone Approved!

_Good luck with your next milestone. Happy coding_
Rindra Josia

**Comment by abeidahmed** [comment]
> **STATUS: APPROVED** 
> **Congratulations**, your project is approved.
> The ERD image has everything required. Milestone Approved!
> 
> _Good luck with your next milestone. Happy coding_
> Rindra Josia

Thanks!

**Pull request merged**
